steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    entrypoint: 'pack'
    args:
      - build
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/inventoryapp
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --publish

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - inventoryapp
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/inventoryapp
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --add-cloudsql-instances=milestone-cst323:us-central1:milestone-cst323-project
      - --set-env-vars=SPRING_DATASOURCE_URL=jdbc:mysql:///inventory_control?cloudSqlInstance=milestone-cst323:us-central1:milestone-cst323-project&socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlRefreshStrategy=lazy,SPRING_DATASOURCE_USERNAME=inventory_user,SPRING_DATASOURCE_PASSWORD=milestonecst323

options:
  logging: CLOUD_LOGGING_ONLY